### PR TITLE
Add quintals and ton aliases

### PR DESCRIPTION
**Pull request by ragarwal6397**
Add the quintal unit/aliases and also add two aliases for ton with the British spelling

### CODE REVIEW

**Comment by ragarwal6397** [comment]
I have signed the CLA!

**Comment by kmcphillips** [comment]
This makes sense. Love the UK spellings for tonne. Thanks for the test coverage.

CI is broken but that's about rails 8 beta and ruby versions. I'll have to look at that.

**Comment by ragarwal6397** [comment]
Thanks @kmcphillips! Rebased on latest main

**Comment by kmcphillips** [comment]
Released in `3.1.0`

**Pull request merged**
